/* DO NOT TOUCH, AUTOGENERATED BY OFFSET.C */

#ifndef _MIPS_OFFSET_H
#define _MIPS_OFFSET_H

/* MIPS pt_regs offsets. */
#define PT_R0     48
#define PT_R1     56
#define PT_R2     64
#define PT_R3     72
#define PT_R4     80
#define PT_R5     88
#define PT_R6     96
#define PT_R7     104
#define PT_R8     112
#define PT_R9     120
#define PT_R10    128
#define PT_R11    136
#define PT_R12    144
#define PT_R13    152
#define PT_R14    160
#define PT_R15    168
#define PT_R16    176
#define PT_R17    184
#define PT_R18    192
#define PT_R19    200
#define PT_R20    208
#define PT_R21    216
#define PT_R22    224
#define PT_R23    232
#define PT_R24    240
#define PT_R25    248
#define PT_R26    256
#define PT_R27    264
#define PT_R28    272
#define PT_R29    280
#define PT_R30    288
#define PT_R31    296
#define PT_LO     312
#define PT_HI     320
#define PT_EPC    344
#define PT_BVADDR 328
#define PT_STATUS 304
#define PT_CAUSE  336
#define PT_SIZE   352

/* MIPS task_struct offsets. */
#define TASK_STATE         0
#define TASK_FLAGS         8
  #define _PT_TRACESYS        0x2
#define TASK_SIGPENDING    16
#define TASK_NEED_RESCHED  40
#define TASK_PTRACE        48
#define TASK_COUNTER       64
#define TASK_NICE          72
#define TASK_MM            88
#define TASK_PROCESSOR     96
#define TASK_PID           228
#define TASK_STRUCT_SIZE   1552

/* MIPS task_struct allocation info. */
#define _THREAD_ORDER    0x0
#define _THREAD_SIZE     0x4000
#define _THREAD_MASK     0x3fff

/* MIPS specific thread_struct offsets. */
#define THREAD_REG16   984
#define THREAD_REG17   992
#define THREAD_REG18   1000
#define THREAD_REG19   1008
#define THREAD_REG20   1016
#define THREAD_REG21   1024
#define THREAD_REG22   1032
#define THREAD_REG23   1040
#define THREAD_REG29   1048
#define THREAD_REG30   1056
#define THREAD_REG31   1064
#define THREAD_STATUS  1072
#define THREAD_FPU     1080
#define THREAD_BVADDR  1344
#define THREAD_BUADDR  1352
#define THREAD_ECODE   1360
#define THREAD_TRAPNO  1368
#define THREAD_MFLAGS  1376
#define THREAD_CURDS   1384
#define THREAD_TRAMP   1392
#define THREAD_OLDCTX  1400

/* Linux mm_struct offsets. */
#define MM_USERS      32
#define MM_PGD        24
#define MM_CONTEXT    232

#define _PAGE_SIZE     0x4000
#define _PAGE_SHIFT    0xe

#define _PGD_T_SIZE    0x8
#define _PMD_T_SIZE    0x8
#define _PTE_T_SIZE    0x8

#define _PGD_T_LOG2    0x3
#define _PMD_T_LOG2    0x3
#define _PTE_T_LOG2    0x3

#define _PMD_SHIFT     0x19
#define _PGDIR_SHIFT   0x25

#define _PGD_ORDER     0x0
#define _PMD_ORDER     0x0
#define _PTE_ORDER     0x0

#define _PTRS_PER_PGD  0x800
#define _PTRS_PER_PMD  0x800
#define _PTRS_PER_PTE  0x800

/* Linux sigcontext offsets. */
#define SC_REGS       0
#define SC_FPREGS     256
#define SC_MDHI       512
#define SC_MDLO       520
#define SC_PC         528
#define SC_STATUS     536
#define SC_FPC_CSR    540
#define SC_FPC_EIR    544
#define SC_CAUSE      552
#define SC_BADVADDR   556

/* Linux 32-bit sigcontext offsets. */
#define SC32_FPREGS     272
#define SC32_FPC_CSR    532
#define SC32_FPC_EIR    536

/* Linux signal numbers. */
#define _SIGHUP     0x1
#define _SIGINT     0x2
#define _SIGQUIT    0x3
#define _SIGILL     0x4
#define _SIGTRAP    0x5
#define _SIGIOT     0x6
#define _SIGABRT    0x6
#define _SIGEMT     0x7
#define _SIGFPE     0x8
#define _SIGKILL    0x9
#define _SIGBUS     0xa
#define _SIGSEGV    0xb
#define _SIGSYS     0xc
#define _SIGPIPE    0xd
#define _SIGALRM    0xe
#define _SIGTERM    0xf
#define _SIGUSR1    0x10
#define _SIGUSR2    0x11
#define _SIGCHLD    0x12
#define _SIGPWR     0x13
#define _SIGWINCH   0x14
#define _SIGURG     0x15
#define _SIGIO      0x16
#define _SIGSTOP    0x17
#define _SIGTSTP    0x18
#define _SIGCONT    0x19
#define _SIGTTIN    0x1a
#define _SIGTTOU    0x1b
#define _SIGVTALRM  0x1c
#define _SIGPROF    0x1d
#define _SIGXCPU    0x1e
#define _SIGXFSZ    0x1f
#endif /* !(_MIPS_OFFSET_H) */
