#
#  Copyright 2007, 2008 Lemote Tec
#  Author: www.lemote.com Inc
#
# Makefile for the loongson2f CPUS, generic files
#

obj-y += mem.o mipsdha.o pci.o clock.o
obj-$(CONFIG_CS5536) += cs5536_vsm.o mfgpt.o
